import React from 'react'
import Head from 'next/head'

export default function article() {
    return (
        <div className="px-4 py-10" >
            <Head>
            <title>Article Preview</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="mx-auto lg:w-3/5 lg:flex lg:flex-row lg:h-auto">
                <img className="w-full h-48 rounded-tr-md rounded-tl-md lg:h-auto lg:w-2/5 lg:rounded-tr-none lg:rounded-bl-md" src="/images/drawers.jpg" alt=""/>
                <div className="p-8 bg-white rounded-br-md rounded-bl-md lg:rounded-bl-none">
                <h2 className="text-lg font-semibold text-gray-600 ">Shift the overall look and feel by adding these wonderful touches to furniture in your name</h2>
                <p className="mt-4 text-sm text-gray-500 ">Ever been a room and felt like something was missing? Pherphs it felt slightly bare and uninviting,
                    I've got some simple tips to help you make any room feel complete.
                </p>
                <div className="flex items-center mt-8 ">
                    <div className="flex items-center">
                        <img className="w-10 h-10 rounded-full" src="/images/avatar-michelle.jpg" alt=""/>
                        <div className="ml-4">
                            <p className="text-sm font-semibold text-gray-600">Michalle Appleton</p>
                            <p className="text-sm text-gray-500">28 Jun 2020</p>
                        </div>
                    </div>
                    <div className="flex items-center justify-center w-8 h-8 ml-auto bg-gray-300 rounded-full">
                        <svg xmlns="http://www.w3.org/2000/svg" width="15" height="13"><path fill="#6E8098" d="M15 6.495L8.766.014V3.88H7.441C3.33 3.88 0 7.039 0 10.936v2.049l.589-.612C2.59 10.294 5.422 9.11 8.39 9.11h.375v3.867L15 6.495z"/></svg>
                    </div>
                </div>
            </div>
            </div>
            
        </div>
    )
}
