import React from 'react'
import Head from 'next/head'

export default function workcation() {
    return (
        <div className="px-4 py-10">
            <Head>
            <title>Workcation Preview</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="max-w-md mx-auto">
                <img className="h-10" src="/images/logo.svg" />
                <img className="mt-6 rounded-lg shadow-xl" src="/images/beach-work.jpg"/>
                <h1 className="mt-6 text-2xl font-bold text-gray-900">
                    You can work from anywhere <span className="text-indigo-500"> Take adventage of it</span>
                </h1>
                <p className="mt-2 text-gray-600">
                    Workcation helps you find work-friendly rentals in beautiful locations so you can enjoy some nice weather even when you are not on vacation.  
                </p>
                <button className="px-4 py-2 mt-2 font-semibold tracking-wider text-white uppercase bg-indigo-500 rounded-lg shadow-lg ">
                    Book your escape
                </button>
            </div>
                
        </div>
    )
}
